## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame:
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,6,Maryville,US,85.30,broken clouds,35.7565,-83.9705,Holiday Inn Express & Suites Alcoa (Knoxville ...
1,15,Hilo,US,79.29,broken clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
2,16,Sterling,US,86.25,broken clouds,39.0062,-77.4286,Hampton Inn & Suites Washington-Dulles Interna...
3,17,Tautira,PF,77.40,light rain,-17.7333,-149.1500,Pension Oaoa
4,18,Maragogi,BR,77.79,clear sky,-9.0122,-35.2225,Salinas do Maragogi All Inclusive Resort

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list:
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame:
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map:

max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# 4b. Display the figure:

fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Trip to Brazil:
brazil_vacation_df=vacation_df.loc[(vacation_df["Country"]=="BR")]
brazil_vacation_df.dropna()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,18,Maragogi,BR,77.79,clear sky,-9.0122,-35.2225,Salinas do Maragogi All Inclusive Resort
10,39,Vilhena,BR,87.87,overcast clouds,-12.7406,-60.1458,Hotel Mirage
17,58,Nísia Floresta,BR,83.21,few clouds,-6.0911,-35.2086,Rancho Crepusculo
20,63,Touros,BR,80.56,overcast clouds,-5.1989,-35.4608,INN NEW HORIZON
39,119,Augusto Corrêa,BR,83.44,overcast clouds,-1.0217,-46.6350,Fazenda Bacuri
42,126,Linhares,BR,75.65,broken clouds,-19.3911,-40.0722,Hotel Conceição
98,276,Ribas do Rio Pardo,BR,86.97,broken clouds,-20.4431,-53.7592,Pousada Avenida
99,278,Carutapera,BR,83.71,overcast clouds,-1.1950,-46.0200,Lidera
137,401,Salinópolis,BR,83.01,overcast clouds,-0.6136,-47.3561,Salinas Park Resort Maçarico AP101
148,440,Jardim,BR,87.60,overcast clouds,-21.4803,-56.1381,Estancia Hotel - Jardim MS
152,450,Cururupu,BR,86.29,broken clouds,-1.8283,-44.8683,POUSADA TRAVÉS'CIA
175,498,Vila Velha,BR,75.15,few clouds,-20.3297,-40.2925,Hotel Vitória Palace
180,527,São João da Barra,BR,77.09,clear sky,-21.6403,-41.0511,Pousada Porto De Canoas
182,533,Guiratinga,BR,88.20,scattered clouds,-16.3494,-53.7583,Hotel Angra do Cerrado - Guiratinga MT
186,539,Olinda,BR,80.33,clear sky,-8.0089,-34.8553,Flat Quatro Rodas Olinda
197,583,Teodoro Sampaio,BR,85.14,overcast clouds,-22.5325,-52.1675,Hotel do Senhor
211,620,Santa Isabel,BR,82.11,few clouds,-23.3156,-46.2214,Chácara Sombra do Altíssimo
221,651,Cabedelo,BR,83.07,few clouds,-6.9811,-34.8339,Pousada Camboinha

In [29]:
brazil_vacation_df.dtypes

City_ID                  int64
City                    object
Country                 object
Max Temp               float64
Current Description     object
Lat                    float64
Lng                    float64
Hotel Name              object
dtype: object

In [9]:
## From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities:

start= input("What city would you like to start your trip at? ")
stop1= input("What city would you like to stop at next? ")
stop2= input("What city would you like to stop at next? ")
stop3=input("What city would you like to stop at next? ")
end= input("What city would you like to end your trip at? ")

What city would you like to start your trip at? Vilhena
What city would you like to stop at next? Jardim
What city would you like to stop at next? Ribas do Rio Pardo
What city would you like to stop at next? Guiratinga
What city would you like to end your trip at? Vilhena

In [26]:
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = brazil_vacation_df.loc[(brazil_vacation_df["City"] == start)]
vacation_start= vacation_start.iloc[0,1]

vacation_stop1 = brazil_vacation_df.loc[(brazil_vacation_df["City"] == stop1)]
vacation_stop1 = vacation_stop1.iloc[0,1]

vacation_stop2 = brazil_vacation_df.loc[(brazil_vacation_df["City"] == stop2)]
vacation_stop2 = vacation_stop2.iloc[0,1]

vacation_stop3 = brazil_vacation_df.loc[(brazil_vacation_df["City"] == stop3)]
vacation_stop3 = vacation_stop3.iloc[0,1]

vacation_end = brazil_vacation_df.loc[(brazil_vacation_df["City"] == end)]
vacation_end = vacation_end.iloc[0,1]

print(f"You start your trip in {vacation_start}, BR")
print(f"Your first stop is {vacation_stop1}, BR" )
print(f"Your first stop is {vacation_stop2}, BR")
print(f"Your first stop is {vacation_stop3}, BR")
print(f"You end your trip in {vacation_end}, BR")

You start your trip in Vilhena, BR
Your first stop is Jardim, BR
Your first stop is Ribas do Rio Pardo, BR
Your first stop is Guiratinga, BR
You end your trip in Vilhena, BR

In [79]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = brazil_vacation_df.iloc[1,5:7].to_numpy()
stop1 = brazil_vacation_df.iloc[9,5:7].to_numpy()
stop2 = brazil_vacation_df.iloc[6,5:7].to_numpy()
stop3 = brazil_vacation_df.iloc[13,5:7].to_numpy()
end = brazil_vacation_df.iloc[1,5:7].to_numpy()

print(f'Your vacation starts in {vacation_start} with Lat-Long {tuple(start)}')
print(f'Your first stop is {vacation_stop1} with Lat-Long {tuple(stop1)}')
print(f'Your second stop is {vacation_stop2} with Lat-Long {tuple(stop2)}')
print(f'Your third stop is {vacation_stop3} with Lat-Long {tuple(stop3)}')
print(f'You end your trip back in {vacation_end} with Lat-Long {tuple(end)}')

Your vacation starts in Vilhena with Lat-Long (-12.7406, -60.1458)
Your first stop is Jardim with Lat-Long (-21.4803, -56.1381)
Your second stop is Ribas do Rio Pardo with Lat-Long (-20.4431, -53.7592)
Your third stop is Guiratinga with Lat-Long (-16.3494, -53.7583)
You end your trip back in Vilhena with Lat-Long (-12.7406, -60.1458)

In [85]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

start= (-12.7406, -60.1458)
stop1= (-21.4803, -56.1381)
stop2= (-20.4431, -53.7592)
stop3= (-16.3494, -53.7583)
end= (-12.7406, -60.1458)

fig=gmaps.figure()
trips_route=gmaps.directions_layer(start, end, 
                                   waypoints=[stop1, stop2, stop3],
                                  travel_mode= 'DRIVING')
fig.add_layer(trips_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [72]:
trip1=brazil_vacation_df.loc[(brazil_vacation_df["City"] == "Vilhena")]
trip2=brazil_vacation_df.loc[(brazil_vacation_df["City"] == "Jardim")]
trip3=brazil_vacation_df.loc[(brazil_vacation_df["City"] == "Ribas do Rio Pardo")]
trip4=brazil_vacation_df.loc[(brazil_vacation_df["City"] == "Guiratinga")]
trip5=brazil_vacation_df.loc[(brazil_vacation_df["City"] == "Vilhena")]

In [73]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([trip1, trip2, trip3, trip4],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,39,Vilhena,BR,87.87,overcast clouds,-12.7406,-60.1458,Hotel Mirage
1,440,Jardim,BR,87.60,overcast clouds,-21.4803,-56.1381,Estancia Hotel - Jardim MS
2,276,Ribas do Rio Pardo,BR,86.97,broken clouds,-20.4431,-53.7592,Pousada Avenida
3,533,Guiratinga,BR,88.20,scattered clouds,-16.3494,-53.7583,Hotel Angra do Cerrado - Guiratinga MT

In [74]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [75]:
# 11a. Add a marker layer for each city to the map.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))